### ISSUE TITLE
Create a Database access module

### ISSUE THREAD

**Issue by bibroy** [bibroy/issues-demo#1]
#### Tasks
- [ ] #2
- [ ] Task list aa
- [ ] Task list bb
- [ ] Task list cc

**Comment by bibroy** [comment]
some comment
